
services:
  registry:
    ports:
      - "5000:5000"
    restart: always
    container_name: registry
    image: registry:2
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
