services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - /vw-data/:/data/
    environment:
      - ADMIN_TOKEN=<MyToken>
    ports:
      - "80:80"
    restart: unless-stopped